# Choose "crm" environment

POST {{base_url}}{{token}}/crm.contact.add
Content-Type: application/json

{
  "fields": {
    "NAME": "Глеб",
    "SECOND_NAME": "Егорович",
    "LAST_NAME": "Титов",
    "OPENED": "Y",
    "ASSIGNED_BY_ID": 1,
    "TYPE_ID": "CLIENT",
    "SOURCE_ID": "SELF"
  },
  "params": {
    "REGISTER_SONET_EVENT": "Y"
  }
}